# chunk_rules.yml
# Only formats with working loaders & chunker strategies are included.
# Extend when a new loader/strategy lands.

# === E-mail ===
eml:
  strategy: by_email_block        # implemented in BaseChunker
  min_tokens: 30
  max_tokens: 250
  overlap: 10
  notes: split on reply blocks; fallback to paragraph

# === Word Processing ===
docx:
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20
  notes: paragraph-aware splitting

rtf:  # handled via the docx loader path
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20

# === PDFs ===
pdf:
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20

# === PowerPoint ===
pptx:
  strategy: by_slide              # one chunk per slide
  min_tokens: 200
  max_tokens: 800
  overlap: 0

# === Plain text ===
txt:
  strategy: split_on_blank_lines  # implemented
  min_tokens: 40                  # after blank-line split, enforce bounds
  max_tokens: 300
  overlap: 15
